/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.SwingConstants;
import registro.Settings;
import toFile.dataType.Base.Cliente;
import toFile.dataType.Complex.DataBase;
import toFile.dataType.Ordinals.OrdinableArray;
import toFile.dataType.Ordinals.OrdinableObject;

/**
 *
 * @author DiegoCG
 */
public class InterfaceCorrupted extends javax.swing.JFrame
{
    DataBase dataBase = registro.Registro.dataBase;
    /*Impostazioni impostazioni = dataBase.impostazioni;*/
    Font font = new Font("Sans-serif", 0, Settings.font);
    Font fontMedium = new Font("Sans-serif", 0, Settings.fontMedium);
    Font fontBig = new Font("Sans-serif", 0, Settings.fontBig);

    boolean inizializzazione = true;
    /**
     * Creates new form Interface
     */
    public InterfaceCorrupted()
    {
        initComponents();
    }
    
    private void log(String msg)
    {
        registro.Registro.log(msg);
    }
    /**
     * update the panel selected
     */
    private void updatejTabbedPane()
    {
        if(!isBilanciaEnable())
        {
            switch(jTabbedPane.getSelectedIndex())
            {
                case 3: updatejPanelClienti();
            }
        }
    }
    
    private boolean isBilanciaEnable()
    {
        return false;
    }
    private void updatejPanelClienti()
    {
        jListClienti.setModel(new javax.swing.AbstractListModel<OrdinableObject>()
        {
            ArrayList<OrdinableObject> oa = dataBase.clienti;
            public int getSize() { return oa.size(); }
            public OrdinableObject getElementAt(int i) { return oa.get(i); }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelBilancia = new javax.swing.JPanel();
        jPanelPesate = new javax.swing.JPanel();
        jPanelTotali = new javax.swing.JPanel();
        jPanelClienti = new javax.swing.JPanel();
        jPanelClienti3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldClientiNome2 = new javax.swing.JTextField();
        jButtonClientiSalva2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldClientiModificaNome = new javax.swing.JTextField();
        jButtonClientiModificaSalva = new javax.swing.JButton();
        jLabelClientiLogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonClientiOrdinamento = new javax.swing.JButton();
        jButtonClientiSu = new javax.swing.JButton();
        jButtonClientiGiu = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListClienti = new javax.swing.JList<>();
        jButtonClientiElimina = new javax.swing.JButton();
        jPanelProdotti = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Voglia di Pane");

        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jTabbedPaneStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelBilanciaLayout = new javax.swing.GroupLayout(jPanelBilancia);
        jPanelBilancia.setLayout(jPanelBilanciaLayout);
        jPanelBilanciaLayout.setHorizontalGroup(
            jPanelBilanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanelBilanciaLayout.setVerticalGroup(
            jPanelBilanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Bilancia", jPanelBilancia);

        javax.swing.GroupLayout jPanelPesateLayout = new javax.swing.GroupLayout(jPanelPesate);
        jPanelPesate.setLayout(jPanelPesateLayout);
        jPanelPesateLayout.setHorizontalGroup(
            jPanelPesateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanelPesateLayout.setVerticalGroup(
            jPanelPesateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Pesate", jPanelPesate);

        javax.swing.GroupLayout jPanelTotaliLayout = new javax.swing.GroupLayout(jPanelTotali);
        jPanelTotali.setLayout(jPanelTotaliLayout);
        jPanelTotaliLayout.setHorizontalGroup(
            jPanelTotaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanelTotaliLayout.setVerticalGroup(
            jPanelTotaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Totali", jPanelTotali);

        jPanelClienti3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuovo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel3.setText("Nome");

        jTextFieldClientiNome.setFont(font);

        jButtonClientiSalva2.setText("Salva");
        jButtonClientiSalva.setFont(font);
        jButtonClientiSalva2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButtonClientiSalva2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientiSalva2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientiNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClientiNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClientiSalva2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modifica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel4.setText("Nome");
        jLabel2.setFont(font);

        jTextFieldClientiModificaNome.setFont(font);

        jButtonClientiModificaSalva.setText("Salva Modifica");
        jButtonClientiModificaSalva.setFont(font);
        jButtonClientiModificaSalva.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButtonClientiModificaSalvaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonClientiModificaSalva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldClientiModificaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldClientiModificaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClientiModificaSalva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelClientiLogo.setHorizontalAlignment(SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelClienti3Layout = new javax.swing.GroupLayout(jPanelClienti3);
        jPanelClienti3.setLayout(jPanelClienti3Layout);
        jPanelClienti3Layout.setHorizontalGroup(
            jPanelClienti3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClienti3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienti3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelClientiLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelClienti3Layout.setVerticalGroup(
            jPanelClienti3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienti3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClientiLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonClientiOrdinamento.setText("Alfabetico");
        jButtonClientiOrdinamento.setFont(font);
        jButtonClientiOrdinamento.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButtonClientiOrdinamentoMouseClicked(evt);
            }
        });

        jButtonClientiSu.setText("Su");
        jButtonClientiSu.setFont(font);
        jButtonClientiSu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButtonClientiSuMouseClicked(evt);
            }
        });

        jButtonClientiGiu.setText("Giù");
        jButtonClientiGiu.setFont(font);
        jButtonClientiGiu.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jButtonClientiGiuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonClientiOrdinamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClientiSu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonClientiGiu)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClientiOrdinamento)
                    .addComponent(jButtonClientiSu)
                    .addComponent(jButtonClientiGiu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jListClienti.setModel(new javax.swing.AbstractListModel<OrdinableObject>()
            {
                ArrayList<OrdinableObject> oa = new ArrayList<OrdinableObject>();
                public int getSize() { return oa.size(); }
                public OrdinableObject getElementAt(int i) { return oa.get(i); }
            });
            jListClienti.setFont(font);
            jListClienti.addListSelectionListener(new javax.swing.event.ListSelectionListener()
            {
                public void valueChanged(javax.swing.event.ListSelectionEvent evt)
                {
                    jListClientiValueChanged(evt);
                }
            });
            jScrollPane6.setViewportView(jListClienti);

            jButtonClientiElimina.setText("Elimina");
            jButtonClientiElimina.setFont(font);
            jButtonClientiElimina.addMouseListener(new java.awt.event.MouseAdapter()
            {
                public void mouseClicked(java.awt.event.MouseEvent evt)
                {
                    jButtonClientiEliminaMouseClicked(evt);
                }
            });

            javax.swing.GroupLayout jPanelClientiLayout = new javax.swing.GroupLayout(jPanelClienti);
            jPanelClienti.setLayout(jPanelClientiLayout);
            jPanelClientiLayout.setHorizontalGroup(
                jPanelClientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelClienti3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelClientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6)
                        .addComponent(jButtonClientiElimina, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanelClientiLayout.setVerticalGroup(
                jPanelClientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelClientiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelClientiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelClienti3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelClientiLayout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonClientiElimina)))
                    .addContainerGap())
            );

            jTabbedPane.addTab("Clienti", jPanelClienti);

            javax.swing.GroupLayout jPanelProdottiLayout = new javax.swing.GroupLayout(jPanelProdotti);
            jPanelProdotti.setLayout(jPanelProdottiLayout);
            jPanelProdottiLayout.setHorizontalGroup(
                jPanelProdottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 690, Short.MAX_VALUE)
            );
            jPanelProdottiLayout.setVerticalGroup(
                jPanelProdottiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 532, Short.MAX_VALUE)
            );

            jTabbedPane.addTab("Prodotti", jPanelProdotti);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientiSalva2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonClientiSalva2MouseClicked
    {//GEN-HEADEREND:event_jButtonClientiSalva2MouseClicked
        /*if(!jTextFieldClientiNome.getText().isEmpty())
        {
            boolean esito = false;
            long id = dataBase.elencoClienti.getNewId();
            long cardinale = dataBase.elencoClienti.getNewCardinale();

            OraFrequente of = new OraFrequente(1440, 1);
            Cliente c = new Cliente(
                id,
                cardinale,
                jTextFieldClientiNome.getText(),
                true,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                of
            );
            esito = dataBase.elencoClienti.add(c);

            if(esito)
            {
                log("Cliente inserito correttamente");
                aggiornaClienti();
                dataBase.salvaClienti();
                infoBox(
                    "Inserimento nuovo Cliente",
                    jTextFieldClientiNome.getText() + " è stato inserito"
                );
                jTextFieldClientiNome.setText("");
            }
            else
            {
                log("Cliente già presente");
            }
        }*/
    }//GEN-LAST:event_jButtonClientiSalva2MouseClicked

    private void jButtonClientiModificaSalvaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonClientiModificaSalvaMouseClicked
    {//GEN-HEADEREND:event_jButtonClientiModificaSalvaMouseClicked
        /*int indiceCliente = jListClienti.getSelectedIndex();
        String nuovoNome = jTextFieldClientiModificaNome.getText();
        if(indiceCliente != -1 && !nuovoNome.isEmpty())
        {
            dataBase.elencoClienti.get(indiceCliente).setNome(nuovoNome);
            aggiornaClienti();
            dataBase.salvaClienti();
            infoBox(
                "Modifica Cliente",
                jTextFieldClientiModificaNome.getText() + " è stato modificato"
            );
            jTextFieldClientiModificaNome.setText("");
        }*/
    }//GEN-LAST:event_jButtonClientiModificaSalvaMouseClicked

    private void jButtonClientiOrdinamentoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonClientiOrdinamentoMouseClicked
    {//GEN-HEADEREND:event_jButtonClientiOrdinamentoMouseClicked
        /*log("jButtonClientiOrdinamentoMouseClicked");
        oClienti.getNext();
        ordinaClienti();
        aggiornajListClienti();*/
    }//GEN-LAST:event_jButtonClientiOrdinamentoMouseClicked

    private void jButtonClientiSuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonClientiSuMouseClicked
    {//GEN-HEADEREND:event_jButtonClientiSuMouseClicked
        //scambiaCardinaleCliente(Verso.DECRESCI);
    }//GEN-LAST:event_jButtonClientiSuMouseClicked

    private void jButtonClientiGiuMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonClientiGiuMouseClicked
    {//GEN-HEADEREND:event_jButtonClientiGiuMouseClicked
        //scambiaCardinaleCliente(Verso.CRESCI);
    }//GEN-LAST:event_jButtonClientiGiuMouseClicked

    private void jListClientiValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListClientiValueChanged
    {//GEN-HEADEREND:event_jListClientiValueChanged
        /*int indiceCliente = jListClienti.getSelectedIndex();
        if(indiceCliente != -1)
        {

            jTextFieldClientiModificaNome.setText(
                dataBase.elencoClienti.get(indiceCliente).getNome()
            );
        }*/
    }//GEN-LAST:event_jListClientiValueChanged

    private void jButtonClientiEliminaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonClientiEliminaMouseClicked
    {//GEN-HEADEREND:event_jButtonClientiEliminaMouseClicked
        /*int indiceCliente = jListClienti.getSelectedIndex();
        if(indiceCliente != -1)
        {
            JLabel label = new JLabel("Vuoi eliminare: " + dataBase.elencoClienti.get(indiceCliente).getNome());
            label.setFont(fontBig);
            int reply = JOptionPane.showConfirmDialog(null, label, "Eliminazione Cliente", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION)
            {
                label = new JLabel("CLIENTE ELIMINATO");
                label.setFont(fontBig);
                JOptionPane.showMessageDialog(null, label);

            }
            if(reply == 0)
            {
                dataBase.elencoClienti.get(indiceCliente).setVisibile(false);
                dataBase.salvaClienti();
                aggiornaClienti();
            }

        }*/
    }//GEN-LAST:event_jButtonClientiEliminaMouseClicked

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jTabbedPaneStateChanged
    {//GEN-HEADEREND:event_jTabbedPaneStateChanged
        updatejTabbedPane();        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientiElimina;
    private javax.swing.JButton jButtonClientiGiu;
    private javax.swing.JButton jButtonClientiModificaSalva;
    private javax.swing.JButton jButtonClientiOrdinamento;
    private javax.swing.JButton jButtonClientiSalva;
    private javax.swing.JButton jButtonClientiSalva1;
    private javax.swing.JButton jButtonClientiSalva2;
    private javax.swing.JButton jButtonClientiSu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClientiLogo;
    private javax.swing.JList<OrdinableObject> jListClienti;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelBilancia;
    private javax.swing.JPanel jPanelClienti;
    private javax.swing.JPanel jPanelClienti1;
    private javax.swing.JPanel jPanelClienti2;
    private javax.swing.JPanel jPanelClienti3;
    private javax.swing.JPanel jPanelPesate;
    private javax.swing.JPanel jPanelProdotti;
    private javax.swing.JPanel jPanelTotali;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldClientiModificaNome;
    private javax.swing.JTextField jTextFieldClientiNome;
    private javax.swing.JTextField jTextFieldClientiNome1;
    private javax.swing.JTextField jTextFieldClientiNome2;
    // End of variables declaration//GEN-END:variables
}
